open-exchange-rates:
    api:
      appId: your app id on register site // https://support.openexchangerates.org/article/121-your-app-id
      baseCurrency: USD
giphy:
  api:
    app_key: your app key on register site // https://support.giphy.com/hc/en-us/articles/360020283431-Request-A-GIPHY-API-Key
    richTag: rich
    brokeTag: broke
